export const products = [
  // Chairs
  {
    id: 1,
    name: "Comfortable Chair",
    category: "Chair",
    price: 99,
    imageUrl: "/assets/chair1.jpg",
    rating: 5,
  },
  {
    id: 2,
    name: "Ergonomic Chair",
    category: "Chair",
    price: 129,
    imageUrl: "/assets/chair2.jpg",
    rating: 4,
  },
  {
    id: 3,
    name: "Stylish Armchair",
    category: "Chair",
    price: 149,
    imageUrl: "/assets/chair3.jpg",
    rating: 3,
  },
  {
    id: 4,
    name: "Leather Recliner",
    category: "Chair",
    price: 199,
    imageUrl: "/assets/chair4.jpg",
    rating: 4,
  },
  {
    id: 5,
    name: "Minimalist Chair",
    category: "Chair",
    price: 89,
    imageUrl: "/assets/chair5.jpg",
    rating: 4.5,
  },

  // Beds
  {
    id: 6,
    name: "King Size Bed",
    category: "Beds",
    price: 299,
    imageUrl: "/assets/bed1.jpg",
    rating: 5,
  },
  {
    id: 7,
    name: "Queen Size Bed",
    category: "Beds",
    price: 249,
    imageUrl: "/assets/bed2.jpg",
    rating: 5,
  },
  {
    id: 8,
    name: "Modern Bed Frame",
    category: "Beds",
    price: 399,
    imageUrl: "/assets/bed3.jpg",
    rating: 3,
  },
  {
    id: 9,
    name: "Platform Bed",
    category: "Beds",
    price: 349,
    imageUrl: "/assets/bed4.jpg",
    rating: 2,
  },
  {
    id: 10,
    name: "Sleigh Bed",
    category: "Beds",
    price: 459,
    imageUrl: "/assets/bed5.jpg",
    rating: 5,
  },

  // Sofas
  {
    id: 11,
    name: "Luxury Sofa",
    category: "Sofa",
    price: 499,
    imageUrl: "/assets/sofa1.jpg",
    rating: 4,
  },
  {
    id: 12,
    name: "Compact Sofa",
    category: "Sofa",
    price: 399,
    imageUrl: "/assets/sofa2.jpg",
    rating: 5,
  },
  {
    id: 13,
    name: "L-shaped Sofa",
    category: "Sofa",
    price: 699,
    imageUrl: "/assets/sofa3.jpg",
    rating: 4,
  },
  {
    id: 14,
    name: "Sofa with Chaise",
    category: "Sofa",
    price: 549,
    imageUrl: "/assets/sofa4.jpg",
    rating: 5,
  },
  {
    id: 15,
    name: "Sectional Sofa",
    category: "Sofa",
    price: 799,
    imageUrl: "/assets/sofa5.jpg",
    rating: 3.6,
  },

  // Lamps
  {
    id: 16,
    name: "Modern Lamp",
    category: "Lamp",
    price: 49,
    imageUrl: "/assets/lamp1.jpg",
    rating: 5,
  },
  {
    id: 17,
    name: "Classic Lamp",
    category: "Lamp",
    price: 59,
    imageUrl: "/assets/lamp2.jpg",
    rating: 4,
  },
  {
    id: 18,
    name: "Wooden Table Lamp",
    category: "Lamp",
    price: 69,
    imageUrl: "/assets/lamp3.jpg",
    rating: 3,
  },
  {
    id: 19,
    name: "Industrial Floor Lamp",
    category: "Lamp",
    price: 89,
    imageUrl: "/assets/lamp4.jpg",
    rating: 5,
  },
  {
    id: 20,
    name: "Vintage Desk Lamp",
    category: "Lamp",
    price: 79,
    imageUrl: "/assets/lamp5.jpg",
    rating: 4,
  },
];
